app:
  # Signing key for HS512 algorithm
  # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
  jwtSecret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
  googleClientId: 542064462283-kudci63303a2nq5o4oldhlej7f1rpd61.apps.googleusercontent.com

logging:
  level:
    org.springframework.security: DEBUG